In [3]:
import pandas as pd

posts = pd.read_parquet("../data/raw/posts.parquet")
comments = pd.read_parquet("../data/raw/comments.parquet")

posts["date"] = pd.to_datetime(posts["created_utc"], unit="s", utc=True)
comments["date"] = pd.to_datetime(comments["created_utc"], unit="s", utc=True)

EURO_START = pd.Timestamp("2024-06-14", tz="UTC")
EURO_END   = pd.Timestamp("2024-07-14", tz="UTC")

def period(ts):
    if ts < EURO_START:
        return "pre"
    elif ts <= EURO_END:
        return "euro"
    else:
        return "post"

posts["period"] = posts["date"].apply(period)
comments["period"] = comments["date"].apply(period)

In [4]:
posts

,post_id,created_utc,title,selftext,author,permalink,url,flair,score,num_comments,post_fullname,date,period
0,1be73q9,1710374403,"„Das ist letztlich auch eine Stärke, wenn man ...",None,agent007653,/r/PolitikBRD/comments/1be73q9/das_ist_letztli...,https://v.redd.it/o13puoo1x6oc1,None,8,1,t3_1be73q9,2024-03-14 00:00:03+00:00,pre
1,1be75t5,1710374538,Der Angriff auf die Demokratie erfolgt durch e...,None,agent007653,/r/PolitikBRD/comments/1be75t5/der_angriff_auf...,https://v.redd.it/yed99bmlx6oc1,None,21,1,t3_1be75t5,2024-03-14 00:02:18+00:00,pre
2,1be7c18,1710374976,"Guten Morgen Fellas, Hr. Ramelow ist, in meine...",None,agent007653,/r/PolitikBRD/comments/1be7c18/guten_morgen_fe...,https://v.redd.it/rmkje7dvy6oc1,None,90,5,t3_1be7c18,2024-03-14 00:09:36+00:00,pre
3,1be7eqe,1710375164,Wenn man nur eine Rede zum AfD-Nazi-Treffen in...,None,agent007653,/r/PolitikBRD/comments/1be7eqe/wenn_man_nur_ei...,https://v.redd.it/jjv2zv6gz6oc1,None,13,1,t3_1be7eqe,2024-03-14 00:12:44+00:00,pre
4,1be7gnv,1710375309,Der #MicDrop des Abends geht an @katharinaward...,None,agent007653,/r/PolitikBRD/comments/1be7gnv/der_micdrop_des...,https://v.redd.it/dscm2z8vz6oc1,None,13,1,t3_1be7gnv,2024-03-14 00:15:09+00:00,pre
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236,1ffecf9,1726177509,"WAS DENN JETZT, HERR KRETSCHMER ?",None,agent007653,/r/PolitikBRD/comments/1ffecf9/was_denn_jetzt_...,https://i.redd.it/l9hn26yw7god1.jpeg,None,13,2,t3_1ffecf9,2024-09-12 21:45:09+00:00,post
1237,1ffeedq,1726177652,HALLO GRÜNE?\nNOCH DA ?,None,agent007653,/r/PolitikBRD/comments/1ffeedq/hallo_grüne_noc...,https://i.redd.it/l56jb76c8god1.jpeg,None,145,96,t3_1ffeedq,2024-09-12 21:47:32+00:00,post
1238,1ffpxpf,1726217025,"Ich habe das Gefühl, die SPD hat Sklaverei lig...",Ich provoziere hier und stelle meine Punkte üb...,BewitchedHare,/r/PolitikBRD/comments/1ffpxpf/ich_habe_das_ge...,https://www.reddit.com/r/PolitikBRD/comments/1...,None,0,21,t3_1ffpxpf,2024-09-13 08:43:45+00:00,post
1239,1fg1cys,1726250907,Neuester EU-Anlauf zur Chatkontrolle: Werden M...,None,EinAndererNutzer,/r/PolitikBRD/comments/1fg1cys/neuester_euanla...,https://www.piratenpartei.de/2024/09/12/neuest...,None,1,1,t3_1fg1cys,2024-09-13 18:08:27+00:00,post
1240,1fg7q3x,1726267520,CDU mit AFD in Sachsen oder Thüringen?,[removed],RoutineSpecific8486,/r/PolitikBRD/comments/1fg7q3x/cdu_mit_afd_in_...,https://www.reddit.com/r/PolitikBRD/comments/1...,None,1,1,t3_1fg7q3x,2024-09-13 22:45:20+00:00,post

In [ ]:
# export posts and comments as csv
posts.to_csv("../data/processed/posts.csv", index=False)
comments.to_csv("../data/processed/comments.csv", index=False)

In [4]:
import pandas as pd

r_deutschland_posts = pd.read_parquet("../data/raw/r_deutschland_posts.parquet")
r_deutschland_comments = pd.read_parquet("../data/raw/r_deutschland_comments.parquet")

r_deutschland_posts["date"] = pd.to_datetime(r_deutschland_posts["created_utc"], unit="s", utc=True)
r_deutschland_comments["date"] = pd.to_datetime(r_deutschland_comments["created_utc"], unit="s", utc=True)

In [5]:
r_deutschland_posts

,post_id,created_utc,title,selftext,author,permalink,url,flair,score,num_comments,post_fullname,date
0,1csi1g4,1715770899,"Travelling to Italy, Slovenia, Croatia in car ...","\nHello,\nI am a student. My fiktionsbescheini...",nanfuz,/r/deutschland/comments/1csi1g4/travelling_to_...,https://i.redd.it/tj52mxcsnk0d1.jpeg,Deutschland,1,1,t3_1csi1g4,2024-05-15 11:01:39+00:00
1,1csnye5,1715787768,Hat jemand WAZ Plus das die Person mir einen B...,None,Fit_Sector_1979,/r/deutschland/comments/1csnye5/hat_jemand_waz...,https://i.redd.it/y3zvibsv1m0d1.png,Nordrhein-Westfalen,1,0,t3_1csnye5,2024-05-15 15:42:48+00:00
2,1ctd6az,1715866866,Historische Unterlagen entdeckt,[removed],MeddL180,/r/deutschland/comments/1ctd6az/historische_un...,https://i.redd.it/xegwrx85ls0d1.png,Nordrhein-Westfalen,1,0,t3_1ctd6az,2024-05-16 13:41:06+00:00
3,1ctmxog,1715891250,Finden das Original Video nicht zum Song,Es war ein Ebay Kleinanzeigen Chat Song über „...,tina4ka,/r/deutschland/comments/1ctmxog/finden_das_ori...,https://i.redd.it/33zekojnlu0d1,Kunst & Kultur,3,1,t3_1ctmxog,2024-05-16 20:27:30+00:00
4,1ctyt2k,1715928393,Spare bares Geld mit fantastischen Rabatten & ...,None,Comfortable_Work5806,/r/deutschland/comments/1ctyt2k/spare_bares_ge...,https://i.redd.it/8ibv9wnsnx0d1.png,Deutschland,1,0,t3_1ctyt2k,2024-05-17 06:46:33+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
373,1fek7r1,1726086362,"Mein LEGO-IDEAS-Modell ""Civil Engineering: Typ...",None,MOCingbird,/r/deutschland/comments/1fek7r1/mein_legoideas...,https://ideas.lego.com/projects/22fc8eca-af29-...,Sachsen,19,8,t3_1fek7r1,2024-09-11 20:26:02+00:00
374,1ff6i63,1726157829,Bad Toilette Handbrause,None,West-Calligrapher110,/r/deutschland/comments/1ff6i63/bad_toilette_h...,https://www.reddit.com/gallery/1ff6euy,Hamburg,1,0,t3_1ff6i63,2024-09-12 16:17:09+00:00
375,1ff8xys,1726163905,Spende für meinen geburtstag,[removed],Illustrious_Band4811,/r/deutschland/comments/1ff8xys/spende_für_mei...,https://i.redd.it/chfqt84j3fod1.jpeg,Deutschland,1,0,t3_1ff8xys,2024-09-12 17:58:25+00:00
376,1ffliuv,1726199165,Das war mein Opa,None,Pleasant_Refuse_2142,/r/deutschland/comments/1ffliuv/das_war_mein_opa/,https://i.redd.it/fadqmigd0iod1.jpeg,Bayern,1,0,t3_1ffliuv,2024-09-13 03:46:05+00:00
377,1fg5hzk,1726261530,Deutschlands Zukunft,\nKurz etwas zu mir als Person: Ich bin 18 Jah...,Neenogotgame,/r/deutschland/comments/1fg5hzk/deutschlands_z...,https://i.redd.it/3g9tyqht5nod1.jpeg,Deutschland,3,6,t3_1fg5hzk,2024-09-13 21:05:30+00:00

In [9]:
rde_posts = pd.read_parquet("../data/raw/r_DE_posts.parquet")
rde_comments = pd.read_parquet("../data/raw/r_DE_comments.parquet")

rde_posts["date"] = pd.to_datetime(rde_posts["created_utc"], unit="s", utc=True)
rde_comments["date"] = pd.to_datetime(rde_comments["created_utc"], unit="s", utc=True)
rde_posts

,post_id,created_utc,title,selftext,author,permalink,url,flair,score,num_comments,post_fullname,date
0,1c3i9td,1713059674,Weiß jemand ihren Namen? (Schlag den Star 1. S...,None,oneboiii,/r/de/comments/1c3i9td/weiß_jemand_ihren_namen...,https://i.redd.it/fer6tnaxpcuc1.jpeg,Hilfe,2,48,t3_1c3i9td,2024-04-14 01:54:34+00:00
1,1c3iho6,1713060362,r/de hat nun 2.000.000 Mitglieder,None,I_am_Nic,/r/de/comments/1c3iho6/rde_hat_nun_2000000_mit...,https://i.redd.it/8enprpxyrcuc1.jpeg,Dienstmeldung,15,10,t3_1c3iho6,2024-04-14 02:06:02+00:00
2,1c3k0jf,1713065540,"1,3 promille",[removed],smalldoor_,/r/de/comments/1c3k0jf/13_promille/,https://www.reddit.com/r/de/comments/1c3k0jf/1...,Nachrichten DE,0,1,t3_1c3k0jf,2024-04-14 03:32:20+00:00
3,1c3kj0m,1713067390,Sonntags-Thread!,"Guten Morgen,\n\nhier der Laberthread für alle...",Tourgott,/r/de/comments/1c3kj0m/sonntagsthread/,https://www.reddit.com/r/de/comments/1c3kj0m/s...,Sonstiges,3,52,t3_1c3kj0m,2024-04-14 04:03:10+00:00
4,1c3lmgj,1713071354,Was mach ich hier 🤣,[removed],MrWasGehtSieDas420,/r/de/comments/1c3lmgj/was_mach_ich_hier/,https://www.reddit.com/r/de/comments/1c3lmgj/w...,Nachrichten DE,1,1,t3_1c3lmgj,2024-04-14 05:09:14+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
15695,1eris6i,1723582433,Wie wird man Stadtplaner,[removed],ro-oope,/r/de/comments/1eris6i/wie_wird_man_stadtplaner/,https://www.reddit.com/r/de/comments/1eris6i/w...,Diskussion/Frage,1,1,t3_1eris6i,2024-08-13 20:53:53+00:00
15696,1erjccx,1723584269,Wieso vermisse ich meine Schwester so extrem?,[removed],Gabriel565656,/r/de/comments/1erjccx/wieso_vermisse_ich_mein...,https://www.reddit.com/r/de/comments/1erjccx/w...,Mental Health,1,0,t3_1erjccx,2024-08-13 21:24:29+00:00
15697,1erjfn9,1723584487,Verurteilter Vergewaltiger Steve van de Velde ...,[removed],NewBoy_Again,/r/de/comments/1erjfn9/verurteilter_vergewalti...,https://www.reddit.com/r/de/comments/1erjfn9/v...,Sport,1,0,t3_1erjfn9,2024-08-13 21:28:07+00:00
15698,1erlaen,1723589071,Idee der FDP: Was für die Abschaffung des Entw...,None,RomanesEuntDomusX,/r/de/comments/1erlaen/idee_der_fdp_was_für_di...,https://www.spiegel.de/politik/deutschland/was...,Kolumne & Interview,2,8,t3_1erlaen,2024-08-13 22:44:31+00:00
15699,1erm1li,1723590946,„Es ist erschreckend“: Konferenz in Berlin bri...,None,GirasoleDE,/r/de/comments/1erm1li/es_ist_erschreckend_kon...,https://www.rnd.de/politik/berlin-trumps-maga-...,Politik,706,152,t3_1erm1li,2024-08-13 23:15:46+00:00

In [10]:
rde_posts.to_csv("../data/processed/r_DE_posts.csv", index=False)
rde_comments.to_csv("../data/processed/r_DE_comments.csv", index=False)